language: node_js
sudo: false
dist: trusty

node_js:
  - "10"

cache:
  directories:
    - node_modules

git:
  depth: 10

jobs:
  include:
    - stage: Static Test
      env:
        - test: Editor Config check
      install:
      - npm i -g echint
      script:
      - echint -i "sri/**/*" -i "public/**/*" -v "tutorials/**/*" -v
